"""update product

Revision ID: a382c99b20a4
Revises: 43f1d5e15f00
Create Date: 2023-12-21 18:13:43.233555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a382c99b20a4"
down_revision: Union[str, None] = "43f1d5e15f00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column(
            "description", sa.String(), server_default="", nullable=False
        ),
    )
    op.add_column(
        "product",
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
    )
    op.drop_column("product", "product_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column(
            "product_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("product", "count")
    op.drop_column("product", "description")
    # ### end Alembic commands ###
